version: "3"
services:
  test:
    build: .
    container_name: fw-alerts-test
    ports:
      - "4200:4200"
    environment:
      PORT: 4200
      NODE_PATH: app/src
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_REGISTER_MODE: auto
    command: test
